topic_list
    - name: sda10f_r1_controller
      ns: sda10f
      group: 1
      joints: ['arm_left_joint_1','arm_left_joint_2','arm_left_joint_3','arm_left_joint_4','arm_left_joint_5','arm_left_joint_6','arm_left_joint_7']
    - name: sda10f_r2_controller
      ns: sda10f
      group: 2
      joints: ['arm_right_joint_1','arm_right_joint_2','arm_right_joint_3','arm_right_joint_4','arm_right_joint_5','arm_right_joint_6','arm_right_joint_7']
    - name: sda10f_b1_controller
      ns: sda10f
      group: 3
      joints: ['torso_joint_b1']
    - name: sda10f_b2_controller
      ns: sda10f
      group: 4
      joints: ['torso_joint_b2']
